### PR TITLE
Social media website - Milestone: deploy #4

### PR DESCRIPTION
**Pull request by lirad**
- Created a Heroku application
- Connected the repo with Heroku for continuous deployment
- Updated readme file with the live version link

### CODE REVIEW

**Review by maelfosso — CHANGES_REQUESTED** [review]
# Changes required

Hello,

Thanks for the well-done job so far. 
The online version is working like a charm :blush:

However there are some `TBA` mention in your README
Kindly complete them and once done, submit a new code review requesr

Thanks
Mael FOSSO

**Review by rOluochKe — APPROVED** [review]
Hello @lirad 
### You have done well so far :clap: However, you have a few issues to fix:-
- [ ] Follow gitflow guideline. PR from development branch to master branch
### Make the changes and submit for another code review. Good luck.
- Happy coding!

**Comment by lirad** [comment]
@rOluochKe My PR is already from development into master, can you help me understand what I am missing?

**Comment by rOluochKe** [comment]
> @rOluochKe My PR is already from development into master, can you help me understand what I am missing?

Sorry, you were right

**Review by rOluochKe — APPROVED** [review]
### You got it right :clap: well done. The project has been approved. Congratulations :boom: :100:
### Merge and submit the project. Good luck with the next one.
- Happy coding!

**Pull request merged**
